USE ROLE DATA_ENGINEER;
USE DATABASE EKART_ANALYSIS_DB;
CREATE DATABASE IF NOT EXISTS EKART_ANALYSIS_DB;
CREATE WAREHOUSE IF NOT EXISTS EKART_WH;
CREATE SCHEMA IF NOT EXISTS BRONZE;
CREATE SCHEMA IF NOT EXISTS SILVER;
CREATE SCHEMA IF NOT EXISTS GOLD;
CREATE SCHEMA IF NOT EXISTS MART;