USE ROLE DATA_ENGINEER;
USE SCHEMA BRONZE;

CREATE STORAGE INTEGRATION EKART_STG_INT
TYPE = EXTERNAL_STAGE
ENABLED = TRUE
STORAGE_PROVIDER = 'AZURE'
AZURE_TENANT_ID = '54cb5640-0ff7-4960-8ed6-0ddec23e5359'
STORAGE_ALLOWED_LOCATIONS = ('azure://storagedatavamshi.blob.core.windows.net/data-source');

DESC INTEGRATION EKART_STG_INT;

CREATE OR REPLACE STAGE EKART_DATA_STG
STORAGE_INTEGRATION = EKART_STG_INT
URL = 'azure://storagedatavamshi.blob.core.windows.net/data-source/auto-inc-data'
FILE_FORMAT = bronze_csv_ff;

LIST @EKART_DATA_STG;

-- First, inspect the raw file to see what's there
SELECT $1, $2, $3 FROM @EKART_DATA_STG (FILE_FORMAT => 'BRONZE_CSV_FF');

CREATE OR REPLACE TABLE BRZ_EKART_ANLYS
USING TEMPLATE (
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(*))
 FROM TABLE(INFER_SCHEMA(
    LOCATION => '@EKART_DATA_STG',
    FILE_FORMAT =>'BRONZE_CSV_IS_FF'
)));

SELECT * FROM BRZ_EKART_ANLYS;

ALTER TABLE BRZ_EKART_ANLYS ADD COLUMN LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP();

ALTER TABLE BRZ_EKART_ANLYS ADD COLUMN LOAD_TS TIMESTAMP_NTZ;

UPDATE BRZ_EKART_ANLYS SET LOAD_TS = CURRENT_TIMESTAMP() WHERE LOAD_TS IS NULL;