USE ROLE DATA_ENGINEER;

CREATE OR REPLACE FILE FORMAT BRONZE_CSV_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1;

  CREATE OR REPLACE FILE FORMAT BRONZE_CSV_IS_FF
  TYPE = CSV
  FIELD_DELIMITER = ','
  PARSE_HEADER = TRUE;